//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShopApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public int OrederNumber { get; set; }
        public int OrderProductID { get; set; }
        public int OrderQuantity { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime OrderDeliveryDate { get; set; }
        public int OrderPickupPointID { get; set; }
        public Nullable<int> OrderUserID { get; set; }
        public int OrderPickCode { get; set; }
        public int OrderSatusID { get; set; }
    
        public virtual PickPoints PickPoints { get; set; }
        public virtual Product Product { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual User User { get; set; }
    }
}
